apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: other-rolebinding
  namespace: other
subjects: #바인딩 시킬 계정
- apiGroup: ""
  kind: ServiceAccount
  name: user1
  namespace: default
roleRef: #계정에 부여할 권한#참조하는 롤
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: other-role 



##바인딩 할 계정정보
##계정에 부여할 권한지정