apiVersion: rbac.authorization.k8s.io/v1
kind: Role  
metadata:
  name: user1-role
  namespace: user-space
rules: 
- apiGroups: [""] # kubernetes API의 Group
  resources: ["pods"] # kubernetes API의 Group에 소속 되어 있는 Kind
  verbs: ["creat","delete","get","watch","patch","list"] # 리소스에 대한 조회/생성/삭제/수정 등의 작업


