apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-httpd-static-web
  labels:
   version: "1.2"
   date: "2023-07"
spec:
  selector:
    matchLabels:
      app: static-web
      server: httpd  
  replicas: 3    
  template:
    metadata:
      labels:
        app: static-web
        server: httpd
        version: "1.2"
    spec:
      containers:
      - name: httpd-static-web
        image: hiwill41/httpd:3.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret
