apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace:
  labels:
   app: static-web
   server: httpd   # 적절한 네임스페이스로 변경하세요.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace:
    labels:
     app: static-web
     server: httpd  # 적절한 네임스페이스로 변경하세요.
roleRef:
  kind: ClusterRole
  name: fluent-bit
  apiGroup: rbac.authorization.k8s.io
