apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    name: vol-pod
spec:
  nodeName: kube-worker-node2
  containers:
  - name: vol-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: host-volume
      mountPath: /usr/share/nginx/html    
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp/pod
      type: DirectoryOrCreate 
  imagePullSecrets:
  - name: docker-pull-secret
      #마운트대상지정, hostpath에 디렉토리에 지정할거다or없으면만들어라, kubelet 기본권한 0755, 파일 0644
      #다른 유형: Directory, File, FileOrCreate
      ##노드의 파일시스템과 파드와 마운트가 이루어지는 형태의 볼륨
      ##파드가 생성된 노드에 마운트가 이루어짐
      ##다른 노드는 마운트 되어있지않음
      ##모든 노드들의 로그 수집을 위한 형태로 사용함
      ##daemonset,pod,deployment,replicaset <- 모든 노드에 파드생성
