apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
      #ReadWriteOnce
      #ReadWriteMany
      #ReadOnlyMany
      #ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain #보존
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share1
    server: 192.168.10.14




