apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
        app: static-web
        version: "1.2"
        server: nginx
        date: "2023-07"
spec:
  type: NodePort
  selector:
    app: static-web
    server: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
