# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "gw" do |gw|
    gw.vm.hostname = "gateway"
    gw.vm.provider "virtualbox" do |vb|
      vb.name = "gateway"
      vb.cpus = 2
      vb.memory = 2048
    end
    gw.vm.network "public_network"  # DHCP
    gw.vm.network "private_network", ip: "192.168.123.254", virtualbox__intnet: true

    gw.vm.provision "shell", inline: <<-SCRIPT
     sudo ip route del default via 10.0.2.2 dev enp0s3
     sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
     sudo sysctl -p
     sudo iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o enp0s8 -j MASQUERADE
     sudo ip route add 192.168.223.0/24 via 192.168.123.10 dev enp0s9
     sudo iptables -t nat -A PREROUTING -d 192.168.101.215 -i enp0s8 -p tcp --dport 80 -j DNAT --to-destination=192.168.123.10:80
    SCRIPT
  end

  config.vm.define "nginx_web" do |nginx_web|
    nginx_web.vm.hostname = "nginx-web-server"
    nginx_web.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-web-server"
      vb.cpus = 2
      vb.memory = 2048
    end
    nginx_web.vm.network "private_network", ip: "192.168.223.10", virtualbox__intnet: true
    nginx_web.vm.provision "shell", inline: <<-SCRIPT
      sudo ip route del default via 10.0.2.2
      sudo ip route add default via 192.168.223.1 dev enp0s8
      sudo apt-get update -y && sudo apt-get install -y nginx      
    SCRIPT
  end

  config.vm.define "apache_web" do |apache_web|
    apache_web.vm.hostname = "apache-web-server"
    apache_web.vm.provider "virtualbox" do |vb|
      vb.name = "apache-web-server"
      vb.cpus = 2
      vb.memory = 2048
    end
    apache_web.vm.network "private_network", ip: "192.168.223.20", virtualbox__intnet: true
    apache_web.vm.provision "shell", inline: <<-SCRIPT
     sudo ip route del default via 10.0.2.2 dev enp0s3
     sudo ip route add default via 192.168.223.1 dev enp0s8
     sudo apt-get update -y && sudo apt-get install -y apache2
    SCRIPT
  end

  config.vm.define "nginx_lb" do |nginx_lb|
    nginx_lb.vm.hostname = "nginx-lb-server"
    nginx_lb.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-lb-server"
      vb.cpus = 2
      vb.memory = 2048
    end
    # ubuntu 20.04 의 인터페이스명 -> enp0s8
    nginx_lb.vm.network "private_network", ip: "192.168.123.10", virtualbox__intnet: true
    # ubuntu 20.04 의 인터페이스명 -> enp0s9
    nginx_lb.vm.network "private_network", ip: "192.168.223.1", virtualbox__intnet: true
    nginx_lb.vm.provision "shell", inline: <<-SCRIPT
     sudo ip route del default via 10.0.2.2 dev enp0s3
     sudo ip route add default via 192.168.123.254 dev enp0s8
     sudo apt-get update -y && sudo apt-get install -y nginx
     sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
     sudo sysctl -p
    SCRIPT
    # sudo vi /etc/nginx/sites-enabled/default 
    #upstream web_lb {
    #server 192.168.223.10;
    #server 192.168.223.20;
    #}
    # sudo systemctl restart nginx 
    #location / {
    #  proxy_pass http://web_lb;    입력
  end

end


