apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  #         분 시        일 월 요일  # 00시 10분,01시 10분,02시 10분..., */10 10분간격            
  schedule: "0  7,12,23  *  *  1-5" ##이게중요, 매 1분마다 실행, 시간마다지정할수도
  successfulJobsHistoryLimit: 5 #기본파드 3개생성인데 5개까지 남겨라
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: alpine
            command: ["/bin/sh","-c","echo 'Job Running'"]
          restartPolicy: OnFailure

#schedule:에서 요일 항목 0:일요일,1:월요일,2:화요일..., 분기 */4